### ISSUE TITLE
Fix code to support newest mirakuru.

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [ClearcodeHQ/pytest-dbfixtures#113]

**Comment by fizyk** [comment]
Just rerun master build, and nothing is actually broken:
https://travis-ci.org/ClearcodeHQ/pytest-dbfixtures/builds/59606936

**Comment by dstufft** [comment]
I did notice that with mirakuru 0.5.0 (but not with mirakuru 0.4.0) that an error is output when the ``__del__`` method is run. Because this is from a ``__del__`` method Python ignores the exception though.

The output is:

```
pg_ctl: directory "/tmp/postgresqldata.5433" does not exist
Exception ignored in: <bound method PostgreSQLExecutor.__del__ of <pytest_dbfixtures.executors.postgresql.PostgreSQLExecutor: "/usr/local..." 0x108af61d0>>
Traceback (most recent call last):
  File "/Users/dstufft/projects/warehouse/.tox/py34/lib/python3.4/site-packages/mirakuru/base.py", line 344, in __del__
    self.kill()
  File "/Users/dstufft/projects/warehouse/.tox/py34/lib/python3.4/site-packages/mirakuru/base.py", line 295, in kill
    if self.running():
  File "/Users/dstufft/projects/warehouse/.tox/py34/lib/python3.4/site-packages/pytest_dbfixtures/executors/postgresql.py", line 94, in running
    shell=True
  File "/Users/dstufft/.pyenv/versions/3.4.3/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '/usr/local/Cellar/postgresql/9.4.1/bin/pg_ctl status -D /tmp/postgresqldata.5433' returned non-zero exit status 4
```

**Comment by fizyk** [comment]
Hmmm... it's probably due to the fact, that the datadir is already deleted. 

PostgreSQLExecutor has to check the datadir existance in running method as well.
