### ISSUE TITLE
Support for parallel testing under pytest-xdist

### ISSUE THREAD

**Issue by dlitz** [ClearcodeHQ/pytest-dbfixtures#78]
It would be nice if this supported parallel testing with pytest-xdist.  Currently, it fails during the collection phase:

```
$ py.test -s -n 2
=========================================================================================== test session starts ===========================================================================================
platform linux2 -- Python 2.7.8 -- py-1.4.24 -- pytest-2.6.2
plugins: dbfixtures, xdist
gw0 C / gw1 CINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/_pytest/main.py", line 82, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/xdist/dsession.py", line 220, in pytest_sessionstart
INTERNALERROR>     self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/xdist/slavemanage.py", line 57, in setup_nodes
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/xdist/slavemanage.py", line 228, in setup
INTERNALERROR>     self.channel.send((self.slaveinput, args, option_dict))
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 681, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1285, in dumps_internal
INTERNALERROR>     return _Serializer().save(obj)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1303, in save
INTERNALERROR>     self._save(obj)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1321, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1402, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1321, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1398, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1392, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File "/tmp/xxv/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 1319, in _save
INTERNALERROR>     raise DumpError("can't serialize %s" % (tp,))
INTERNALERROR> DumpError: can't serialize <class 'path.path'>
```

**Comment by mmaslowskicc** [comment]
Now xdist works with `-n1` used in the CI builds. Having more workers requires using random port numbers.

Can we use randomized port numbers by default? I'm not sure if compatibility with packages using it with the default fixtures and hardcoded port numbers in tests is needed.

**Comment by fizyk** [comment]
:+1: although'd do it as a part of #160
